@host=http://localhost:5129
@hostId=dc16d820-a297-4618-88c4-570fedd91cdf
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MWEyNzMzMi1kODdhLTQ4YWItYWEwOC02NDc0OTdlMjU3NGYiLCJnaXZlbl9uYW1lIjoiVGF3aGlkdXIgIiwiZmFtaWx5X25hbWUiOiJSYWhtYW4iLCJqdGkiOiJlMDM0OTAyNy1mMDE5LTQzZDAtODM1Mi0wMDEyYmE1Mzk4MjEiLCJleHAiOjE2OTAwNDkyMTksImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.fPY5RgXntyN5RuRazyIKcnRaxz5DasIagG86fr_UkiE

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}