@host=http://localhost:5129

GET {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZTJlNzU3ZS1lMzBkLTRjOWUtOTFiNy0yNWM5ZTIxN2FkZjUiLCJnaXZlbl9uYW1lIjoiVGF3aGlkdXIgIiwiZmFtaWx5X25hbWUiOiJSYWhtYW4iLCJqdGkiOiJlZjhlYzMyMi0zYjVlLTQwNjQtODRhNC0wZGQzMzk4ZDI3MDEiLCJleHAiOjE2ODk5NDM0MjcsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.uDY1OwnMSpvuNMaAToHvUM-dEM1WLuYLPuifUNDpOuk