@host = http://localhost:5129

GET   {{host}}/dinners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiZjY3ZGJhYi1hNDRmLTQyNGMtOTYwZS1hNjZhMTQ1YzZkZmUiLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwianRpIjoiNDA2NmVkMGEtY2FhMi00ZjU2LWFlNDItZDZjNDY1MTIwZGNkIiwiZXhwIjoxNjg5NzkwMTYyLCJpc3MiOiJCdWJlckRpbm5lciIsImF1ZCI6IkJ1YmVyRGlubmVyIn0.PXp2p0kOFCCUfIJMw1E5bapRdTTNmLJY2oa7jEuvXX4