@host=http://localhost:5129

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Tawhidur ",
    "lastName": "Rahman",
    "email": "tawhidur@example.com",
    "password": "12345"
}