@host=http://localhost:5129
@hostId=dc16d820-a297-4618-88c4-570fedd91cdf
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYmFlMWU5Mi1mOTcwLTQzZDEtYWY4My01MThhZTMyYzIwMTIiLCJnaXZlbl9uYW1lIjoiVGF3aGlkdXIgIiwiZmFtaWx5X25hbWUiOiJSYWhtYW4iLCJqdGkiOiIzNjA5ZmY1Mi05MjQwLTRmYjktYWE2OC01ZmQzZjc0YWYwY2YiLCJleHAiOjE2ODk5NDczNDcsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.m1CBRxhzGLbxGn0z7iZc25remmFnbqN6_bISxFGFy98

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}