@host=http://localhost:5129
@hostId=dc16d820-a297-4618-88c4-570fedd91cdf
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxOWI2ZjAwYS1iYTQ4LTRhYWUtYjBhOC02ZWQ3OTRlYmM4NzMiLCJnaXZlbl9uYW1lIjoiVGF3aGlkdXIgIiwiZmFtaWx5X25hbWUiOiJSYWhtYW4iLCJqdGkiOiJlMjJkZjgyMS1kZGQxLTRiMWYtODlmNC01MDdiYjY4MjI1YWQiLCJleHAiOjE2ODk5NTE0NzYsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXIifQ.6_ylRM2PHTfzO5tONRQ03y39SkX-4448zgG8j8BNGT4

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Yummy Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}